//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 07:03:31 PM EEST 
//


package com.onenetwork.model.nr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.onenetwork.model.position.Position;


/**
 * <p>Java class for N3RecordDataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="N3RecordDataElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="controlIdentifier" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="recordType" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="districtOrPortOfEntryOrSummary" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="brokerNumberOrEntryFilerCode" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="entryNumber" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="entryTypeCode" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="importerOfRecordNumber" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="entryDate" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="extensionOrSuspensionCodeFirst" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="numberOfTimesExtended" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="extensionOrSuspensionNoticeDate" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="brokerReferenceNumber" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="extensionOrSuspensionCodeSecond" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="extensionOrSuspensionCodeThird" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="extensionOrSuspensionCodeFourth" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="defaultControlIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="messageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endPositionOfControlIdentifier" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "N3RecordDataElement", propOrder = {
    "controlIdentifier",
    "recordType",
    "districtOrPortOfEntryOrSummary",
    "brokerNumberOrEntryFilerCode",
    "entryNumber",
    "entryTypeCode",
    "importerOfRecordNumber",
    "entryDate",
    "extensionOrSuspensionCodeFirst",
    "numberOfTimesExtended",
    "extensionOrSuspensionNoticeDate",
    "brokerReferenceNumber",
    "extensionOrSuspensionCodeSecond",
    "extensionOrSuspensionCodeThird",
    "extensionOrSuspensionCodeFourth",
    "defaultControlIdentifier",
    "messageType",
    "endPositionOfControlIdentifier"
})
public class N3RecordDataElement {

    @XmlElement(required = true)
    protected Position controlIdentifier;
    @XmlElement(required = true)
    protected Position recordType;
    @XmlElement(required = true)
    protected Position districtOrPortOfEntryOrSummary;
    @XmlElement(required = true)
    protected Position brokerNumberOrEntryFilerCode;
    @XmlElement(required = true)
    protected Position entryNumber;
    @XmlElement(required = true)
    protected Position entryTypeCode;
    @XmlElement(required = true)
    protected Position importerOfRecordNumber;
    @XmlElement(required = true)
    protected Position entryDate;
    @XmlElement(required = true)
    protected Position extensionOrSuspensionCodeFirst;
    @XmlElement(required = true)
    protected Position numberOfTimesExtended;
    @XmlElement(required = true)
    protected Position extensionOrSuspensionNoticeDate;
    @XmlElement(required = true)
    protected Position brokerReferenceNumber;
    @XmlElement(required = true)
    protected Position extensionOrSuspensionCodeSecond;
    @XmlElement(required = true)
    protected Position extensionOrSuspensionCodeThird;
    @XmlElement(required = true)
    protected Position extensionOrSuspensionCodeFourth;
    @XmlElement(defaultValue = "N3")
    protected String defaultControlIdentifier;
    @XmlElement(defaultValue = "NR")
    protected String messageType;
    @XmlElement(defaultValue = "2")
    protected Integer endPositionOfControlIdentifier;

    /**
     * Gets the value of the controlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getControlIdentifier() {
        return controlIdentifier;
    }

    /**
     * Sets the value of the controlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setControlIdentifier(Position value) {
        this.controlIdentifier = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setRecordType(Position value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the districtOrPortOfEntryOrSummary property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getDistrictOrPortOfEntryOrSummary() {
        return districtOrPortOfEntryOrSummary;
    }

    /**
     * Sets the value of the districtOrPortOfEntryOrSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setDistrictOrPortOfEntryOrSummary(Position value) {
        this.districtOrPortOfEntryOrSummary = value;
    }

    /**
     * Gets the value of the brokerNumberOrEntryFilerCode property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getBrokerNumberOrEntryFilerCode() {
        return brokerNumberOrEntryFilerCode;
    }

    /**
     * Sets the value of the brokerNumberOrEntryFilerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setBrokerNumberOrEntryFilerCode(Position value) {
        this.brokerNumberOrEntryFilerCode = value;
    }

    /**
     * Gets the value of the entryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getEntryNumber() {
        return entryNumber;
    }

    /**
     * Sets the value of the entryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setEntryNumber(Position value) {
        this.entryNumber = value;
    }

    /**
     * Gets the value of the entryTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getEntryTypeCode() {
        return entryTypeCode;
    }

    /**
     * Sets the value of the entryTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setEntryTypeCode(Position value) {
        this.entryTypeCode = value;
    }

    /**
     * Gets the value of the importerOfRecordNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getImporterOfRecordNumber() {
        return importerOfRecordNumber;
    }

    /**
     * Sets the value of the importerOfRecordNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setImporterOfRecordNumber(Position value) {
        this.importerOfRecordNumber = value;
    }

    /**
     * Gets the value of the entryDate property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getEntryDate() {
        return entryDate;
    }

    /**
     * Sets the value of the entryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setEntryDate(Position value) {
        this.entryDate = value;
    }

    /**
     * Gets the value of the extensionOrSuspensionCodeFirst property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getExtensionOrSuspensionCodeFirst() {
        return extensionOrSuspensionCodeFirst;
    }

    /**
     * Sets the value of the extensionOrSuspensionCodeFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setExtensionOrSuspensionCodeFirst(Position value) {
        this.extensionOrSuspensionCodeFirst = value;
    }

    /**
     * Gets the value of the numberOfTimesExtended property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getNumberOfTimesExtended() {
        return numberOfTimesExtended;
    }

    /**
     * Sets the value of the numberOfTimesExtended property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setNumberOfTimesExtended(Position value) {
        this.numberOfTimesExtended = value;
    }

    /**
     * Gets the value of the extensionOrSuspensionNoticeDate property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getExtensionOrSuspensionNoticeDate() {
        return extensionOrSuspensionNoticeDate;
    }

    /**
     * Sets the value of the extensionOrSuspensionNoticeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setExtensionOrSuspensionNoticeDate(Position value) {
        this.extensionOrSuspensionNoticeDate = value;
    }

    /**
     * Gets the value of the brokerReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getBrokerReferenceNumber() {
        return brokerReferenceNumber;
    }

    /**
     * Sets the value of the brokerReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setBrokerReferenceNumber(Position value) {
        this.brokerReferenceNumber = value;
    }

    /**
     * Gets the value of the extensionOrSuspensionCodeSecond property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getExtensionOrSuspensionCodeSecond() {
        return extensionOrSuspensionCodeSecond;
    }

    /**
     * Sets the value of the extensionOrSuspensionCodeSecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setExtensionOrSuspensionCodeSecond(Position value) {
        this.extensionOrSuspensionCodeSecond = value;
    }

    /**
     * Gets the value of the extensionOrSuspensionCodeThird property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getExtensionOrSuspensionCodeThird() {
        return extensionOrSuspensionCodeThird;
    }

    /**
     * Sets the value of the extensionOrSuspensionCodeThird property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setExtensionOrSuspensionCodeThird(Position value) {
        this.extensionOrSuspensionCodeThird = value;
    }

    /**
     * Gets the value of the extensionOrSuspensionCodeFourth property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getExtensionOrSuspensionCodeFourth() {
        return extensionOrSuspensionCodeFourth;
    }

    /**
     * Sets the value of the extensionOrSuspensionCodeFourth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setExtensionOrSuspensionCodeFourth(Position value) {
        this.extensionOrSuspensionCodeFourth = value;
    }

    /**
     * Gets the value of the defaultControlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultControlIdentifier() {
        return defaultControlIdentifier;
    }

    /**
     * Sets the value of the defaultControlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultControlIdentifier(String value) {
        this.defaultControlIdentifier = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the endPositionOfControlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndPositionOfControlIdentifier() {
        return endPositionOfControlIdentifier;
    }

    /**
     * Sets the value of the endPositionOfControlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndPositionOfControlIdentifier(Integer value) {
        this.endPositionOfControlIdentifier = value;
    }

}
