//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:26:39 PM EEST 
//


package com.onenetwork.model.sn_us_isf10;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.onenetwork.model.sn_us_isf10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.onenetwork.model.sn_us_isf10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SNUSISF10Global }
     * 
     */
    public SNUSISF10Global createSNUSISF10Global() {
        return new SNUSISF10Global();
    }

    /**
     * Create an instance of {@link SF10RecordDataElement }
     * 
     */
    public SF10RecordDataElement createSF10RecordDataElement() {
        return new SF10RecordDataElement();
    }

    /**
     * Create an instance of {@link SF13RecordDataElement }
     * 
     */
    public SF13RecordDataElement createSF13RecordDataElement() {
        return new SF13RecordDataElement();
    }

    /**
     * Create an instance of {@link SF15RecordDataElement }
     * 
     */
    public SF15RecordDataElement createSF15RecordDataElement() {
        return new SF15RecordDataElement();
    }

    /**
     * Create an instance of {@link SF20RecordDataElement }
     * 
     */
    public SF20RecordDataElement createSF20RecordDataElement() {
        return new SF20RecordDataElement();
    }

    /**
     * Create an instance of {@link SF25RecordDataElement }
     * 
     */
    public SF25RecordDataElement createSF25RecordDataElement() {
        return new SF25RecordDataElement();
    }

    /**
     * Create an instance of {@link SF30RecordDataElement }
     * 
     */
    public SF30RecordDataElement createSF30RecordDataElement() {
        return new SF30RecordDataElement();
    }

    /**
     * Create an instance of {@link SF31RecordDataElement }
     * 
     */
    public SF31RecordDataElement createSF31RecordDataElement() {
        return new SF31RecordDataElement();
    }

    /**
     * Create an instance of {@link SF35RecordDataElement }
     * 
     */
    public SF35RecordDataElement createSF35RecordDataElement() {
        return new SF35RecordDataElement();
    }

    /**
     * Create an instance of {@link SF36RecordDataElement }
     * 
     */
    public SF36RecordDataElement createSF36RecordDataElement() {
        return new SF36RecordDataElement();
    }

    /**
     * Create an instance of {@link SF40RecordDataElement }
     * 
     */
    public SF40RecordDataElement createSF40RecordDataElement() {
        return new SF40RecordDataElement();
    }

    /**
     * Create an instance of {@link SF50RecordDataElement }
     * 
     */
    public SF50RecordDataElement createSF50RecordDataElement() {
        return new SF50RecordDataElement();
    }

    /**
     * Create an instance of {@link SF90RecordDataElement }
     * 
     */
    public SF90RecordDataElement createSF90RecordDataElement() {
        return new SF90RecordDataElement();
    }

}
