//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 11:00:31 PM EEST 
//


package com.onenetwork.model.so;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SO10RecordDataElement" type="{http://www.model.onenetwork.com/so}SO10RecordDataElement"/&gt;
 *         &lt;element name="SO20RecordDataElement" type="{http://www.model.onenetwork.com/so}SO20RecordDataElement"/&gt;
 *         &lt;element name="SO30RecordDataElement" type="{http://www.model.onenetwork.com/so}SO30RecordDataElement"/&gt;
 *         &lt;element name="SO40RecordDataElement" type="{http://www.model.onenetwork.com/so}SO40RecordDataElement"/&gt;
 *         &lt;element name="SO42RecordDataElement" type="{http://www.model.onenetwork.com/so}SO42RecordDataElement"/&gt;
 *         &lt;element name="SO50RecordDataElement" type="{http://www.model.onenetwork.com/so}SO50RecordDataElement"/&gt;
 *         &lt;element name="SO60RecordDataElement" type="{http://www.model.onenetwork.com/so}SO60RecordDataElement"/&gt;
 *         &lt;element name="SO70RecordDataElement" type="{http://www.model.onenetwork.com/so}SO70RecordDataElement"/&gt;
 *         &lt;element name="SO71RecordDataElement" type="{http://www.model.onenetwork.com/so}SO71RecordDataElement"/&gt;
 *         &lt;element name="SO72RecordDataElement" type="{http://www.model.onenetwork.com/so}SO72RecordDataElement"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "so10RecordDataElement",
    "so20RecordDataElement",
    "so30RecordDataElement",
    "so40RecordDataElement",
    "so42RecordDataElement",
    "so50RecordDataElement",
    "so60RecordDataElement",
    "so70RecordDataElement",
    "so71RecordDataElement",
    "so72RecordDataElement"
})
@XmlRootElement(name = "SOGlobal")
public class SOGlobal {

    @XmlElement(name = "SO10RecordDataElement", required = true)
    protected SO10RecordDataElement so10RecordDataElement;
    @XmlElement(name = "SO20RecordDataElement", required = true)
    protected SO20RecordDataElement so20RecordDataElement;
    @XmlElement(name = "SO30RecordDataElement", required = true)
    protected SO30RecordDataElement so30RecordDataElement;
    @XmlElement(name = "SO40RecordDataElement", required = true)
    protected SO40RecordDataElement so40RecordDataElement;
    @XmlElement(name = "SO42RecordDataElement", required = true)
    protected SO42RecordDataElement so42RecordDataElement;
    @XmlElement(name = "SO50RecordDataElement", required = true)
    protected SO50RecordDataElement so50RecordDataElement;
    @XmlElement(name = "SO60RecordDataElement", required = true)
    protected SO60RecordDataElement so60RecordDataElement;
    @XmlElement(name = "SO70RecordDataElement", required = true)
    protected SO70RecordDataElement so70RecordDataElement;
    @XmlElement(name = "SO71RecordDataElement", required = true)
    protected SO71RecordDataElement so71RecordDataElement;
    @XmlElement(name = "SO72RecordDataElement", required = true)
    protected SO72RecordDataElement so72RecordDataElement;

    /**
     * Gets the value of the so10RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO10RecordDataElement }
     *     
     */
    public SO10RecordDataElement getSO10RecordDataElement() {
        return so10RecordDataElement;
    }

    /**
     * Sets the value of the so10RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO10RecordDataElement }
     *     
     */
    public void setSO10RecordDataElement(SO10RecordDataElement value) {
        this.so10RecordDataElement = value;
    }

    /**
     * Gets the value of the so20RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO20RecordDataElement }
     *     
     */
    public SO20RecordDataElement getSO20RecordDataElement() {
        return so20RecordDataElement;
    }

    /**
     * Sets the value of the so20RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO20RecordDataElement }
     *     
     */
    public void setSO20RecordDataElement(SO20RecordDataElement value) {
        this.so20RecordDataElement = value;
    }

    /**
     * Gets the value of the so30RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO30RecordDataElement }
     *     
     */
    public SO30RecordDataElement getSO30RecordDataElement() {
        return so30RecordDataElement;
    }

    /**
     * Sets the value of the so30RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO30RecordDataElement }
     *     
     */
    public void setSO30RecordDataElement(SO30RecordDataElement value) {
        this.so30RecordDataElement = value;
    }

    /**
     * Gets the value of the so40RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO40RecordDataElement }
     *     
     */
    public SO40RecordDataElement getSO40RecordDataElement() {
        return so40RecordDataElement;
    }

    /**
     * Sets the value of the so40RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO40RecordDataElement }
     *     
     */
    public void setSO40RecordDataElement(SO40RecordDataElement value) {
        this.so40RecordDataElement = value;
    }

    /**
     * Gets the value of the so42RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO42RecordDataElement }
     *     
     */
    public SO42RecordDataElement getSO42RecordDataElement() {
        return so42RecordDataElement;
    }

    /**
     * Sets the value of the so42RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO42RecordDataElement }
     *     
     */
    public void setSO42RecordDataElement(SO42RecordDataElement value) {
        this.so42RecordDataElement = value;
    }

    /**
     * Gets the value of the so50RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO50RecordDataElement }
     *     
     */
    public SO50RecordDataElement getSO50RecordDataElement() {
        return so50RecordDataElement;
    }

    /**
     * Sets the value of the so50RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO50RecordDataElement }
     *     
     */
    public void setSO50RecordDataElement(SO50RecordDataElement value) {
        this.so50RecordDataElement = value;
    }

    /**
     * Gets the value of the so60RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO60RecordDataElement }
     *     
     */
    public SO60RecordDataElement getSO60RecordDataElement() {
        return so60RecordDataElement;
    }

    /**
     * Sets the value of the so60RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO60RecordDataElement }
     *     
     */
    public void setSO60RecordDataElement(SO60RecordDataElement value) {
        this.so60RecordDataElement = value;
    }

    /**
     * Gets the value of the so70RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO70RecordDataElement }
     *     
     */
    public SO70RecordDataElement getSO70RecordDataElement() {
        return so70RecordDataElement;
    }

    /**
     * Sets the value of the so70RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO70RecordDataElement }
     *     
     */
    public void setSO70RecordDataElement(SO70RecordDataElement value) {
        this.so70RecordDataElement = value;
    }

    /**
     * Gets the value of the so71RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO71RecordDataElement }
     *     
     */
    public SO71RecordDataElement getSO71RecordDataElement() {
        return so71RecordDataElement;
    }

    /**
     * Sets the value of the so71RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO71RecordDataElement }
     *     
     */
    public void setSO71RecordDataElement(SO71RecordDataElement value) {
        this.so71RecordDataElement = value;
    }

    /**
     * Gets the value of the so72RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SO72RecordDataElement }
     *     
     */
    public SO72RecordDataElement getSO72RecordDataElement() {
        return so72RecordDataElement;
    }

    /**
     * Sets the value of the so72RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SO72RecordDataElement }
     *     
     */
    public void setSO72RecordDataElement(SO72RecordDataElement value) {
        this.so72RecordDataElement = value;
    }

}
