//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 03:53:23 PM EEST 
//


package com.onenetwork.model.ae_ax.e0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.onenetwork.model.custom_object.CustomObject;
import com.onenetwork.model.position.Position;


/**
 * <p>Java class for E0RecordDataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="E0RecordDataElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="controlIdentifier" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="referenceDataTypeCode" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="occurrencePosition" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="referenceIdConstant" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="referenceDataText" type="{http://www.model.onenetwork.com/custom_object}CustomObject"/&gt;
 *         &lt;element name="defaultControlIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="messageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "E0RecordDataElement", propOrder = {
    "controlIdentifier",
    "referenceDataTypeCode",
    "occurrencePosition",
    "referenceIdConstant",
    "referenceDataText",
    "defaultControlIdentifier",
    "messageType"
})
public class E0RecordDataElement {

    @XmlElement(required = true)
    protected Position controlIdentifier;
    @XmlElement(required = true)
    protected Position referenceDataTypeCode;
    @XmlElement(required = true)
    protected Position occurrencePosition;
    @XmlElement(required = true)
    protected Position referenceIdConstant;
    @XmlElement(required = true)
    protected CustomObject referenceDataText;
    @XmlElement(defaultValue = "E0")
    protected String defaultControlIdentifier;
    @XmlElement(defaultValue = "AE|AX")
    protected String messageType;

    /**
     * Gets the value of the controlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getControlIdentifier() {
        return controlIdentifier;
    }

    /**
     * Sets the value of the controlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setControlIdentifier(Position value) {
        this.controlIdentifier = value;
    }

    /**
     * Gets the value of the referenceDataTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getReferenceDataTypeCode() {
        return referenceDataTypeCode;
    }

    /**
     * Sets the value of the referenceDataTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setReferenceDataTypeCode(Position value) {
        this.referenceDataTypeCode = value;
    }

    /**
     * Gets the value of the occurrencePosition property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getOccurrencePosition() {
        return occurrencePosition;
    }

    /**
     * Sets the value of the occurrencePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setOccurrencePosition(Position value) {
        this.occurrencePosition = value;
    }

    /**
     * Gets the value of the referenceIdConstant property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getReferenceIdConstant() {
        return referenceIdConstant;
    }

    /**
     * Sets the value of the referenceIdConstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setReferenceIdConstant(Position value) {
        this.referenceIdConstant = value;
    }

    /**
     * Gets the value of the referenceDataText property.
     * 
     * @return
     *     possible object is
     *     {@link CustomObject }
     *     
     */
    public CustomObject getReferenceDataText() {
        return referenceDataText;
    }

    /**
     * Sets the value of the referenceDataText property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomObject }
     *     
     */
    public void setReferenceDataText(CustomObject value) {
        this.referenceDataText = value;
    }

    /**
     * Gets the value of the defaultControlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultControlIdentifier() {
        return defaultControlIdentifier;
    }

    /**
     * Sets the value of the defaultControlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultControlIdentifier(String value) {
        this.defaultControlIdentifier = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

}
