//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 01:53:37 PM EEST 
//


package com.onenetwork.model.ae_ax.numbers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.onenetwork.model.position.Position;


/**
 * <p>Java class for FiftyRecordDataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiftyRecordDataElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="controlIdentifier" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="htsNumber" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="dutyAmount" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="valueOfGoodsAmount" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="quantityFirst" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="unitOfMeasureCodeFirst" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="quantitySecond" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="unitOfMeasureCodeSecond" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="quantityThird" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="unitOfMeasureCodeThird" type="{http://www.model.onenetwork.com/position}Position"/&gt;
 *         &lt;element name="defaultControlIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="messageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiftyRecordDataElement", propOrder = {
    "controlIdentifier",
    "htsNumber",
    "dutyAmount",
    "valueOfGoodsAmount",
    "quantityFirst",
    "unitOfMeasureCodeFirst",
    "quantitySecond",
    "unitOfMeasureCodeSecond",
    "quantityThird",
    "unitOfMeasureCodeThird",
    "defaultControlIdentifier",
    "messageType"
})
public class FiftyRecordDataElement {

    @XmlElement(required = true)
    protected Position controlIdentifier;
    @XmlElement(required = true)
    protected Position htsNumber;
    @XmlElement(required = true)
    protected Position dutyAmount;
    @XmlElement(required = true)
    protected Position valueOfGoodsAmount;
    @XmlElement(required = true)
    protected Position quantityFirst;
    @XmlElement(required = true)
    protected Position unitOfMeasureCodeFirst;
    @XmlElement(required = true)
    protected Position quantitySecond;
    @XmlElement(required = true)
    protected Position unitOfMeasureCodeSecond;
    @XmlElement(required = true)
    protected Position quantityThird;
    @XmlElement(required = true)
    protected Position unitOfMeasureCodeThird;
    @XmlElement(defaultValue = "50")
    protected String defaultControlIdentifier;
    @XmlElement(defaultValue = "AE|AX")
    protected String messageType;

    /**
     * Gets the value of the controlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getControlIdentifier() {
        return controlIdentifier;
    }

    /**
     * Sets the value of the controlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setControlIdentifier(Position value) {
        this.controlIdentifier = value;
    }

    /**
     * Gets the value of the htsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getHtsNumber() {
        return htsNumber;
    }

    /**
     * Sets the value of the htsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setHtsNumber(Position value) {
        this.htsNumber = value;
    }

    /**
     * Gets the value of the dutyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getDutyAmount() {
        return dutyAmount;
    }

    /**
     * Sets the value of the dutyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setDutyAmount(Position value) {
        this.dutyAmount = value;
    }

    /**
     * Gets the value of the valueOfGoodsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getValueOfGoodsAmount() {
        return valueOfGoodsAmount;
    }

    /**
     * Sets the value of the valueOfGoodsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setValueOfGoodsAmount(Position value) {
        this.valueOfGoodsAmount = value;
    }

    /**
     * Gets the value of the quantityFirst property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getQuantityFirst() {
        return quantityFirst;
    }

    /**
     * Sets the value of the quantityFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setQuantityFirst(Position value) {
        this.quantityFirst = value;
    }

    /**
     * Gets the value of the unitOfMeasureCodeFirst property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getUnitOfMeasureCodeFirst() {
        return unitOfMeasureCodeFirst;
    }

    /**
     * Sets the value of the unitOfMeasureCodeFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setUnitOfMeasureCodeFirst(Position value) {
        this.unitOfMeasureCodeFirst = value;
    }

    /**
     * Gets the value of the quantitySecond property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getQuantitySecond() {
        return quantitySecond;
    }

    /**
     * Sets the value of the quantitySecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setQuantitySecond(Position value) {
        this.quantitySecond = value;
    }

    /**
     * Gets the value of the unitOfMeasureCodeSecond property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getUnitOfMeasureCodeSecond() {
        return unitOfMeasureCodeSecond;
    }

    /**
     * Sets the value of the unitOfMeasureCodeSecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setUnitOfMeasureCodeSecond(Position value) {
        this.unitOfMeasureCodeSecond = value;
    }

    /**
     * Gets the value of the quantityThird property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getQuantityThird() {
        return quantityThird;
    }

    /**
     * Sets the value of the quantityThird property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setQuantityThird(Position value) {
        this.quantityThird = value;
    }

    /**
     * Gets the value of the unitOfMeasureCodeThird property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getUnitOfMeasureCodeThird() {
        return unitOfMeasureCodeThird;
    }

    /**
     * Sets the value of the unitOfMeasureCodeThird property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setUnitOfMeasureCodeThird(Position value) {
        this.unitOfMeasureCodeThird = value;
    }

    /**
     * Gets the value of the defaultControlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultControlIdentifier() {
        return defaultControlIdentifier;
    }

    /**
     * Sets the value of the defaultControlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultControlIdentifier(String value) {
        this.defaultControlIdentifier = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

}
