//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 02:06:22 PM EEST 
//


package com.onenetwork.model.ae_ax.numbers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Numbers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Numbers"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EightyEightRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}EightyEightRecordDataElement"/&gt;
 *         &lt;element name="EightyNineRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}EightyNineRecordDataElement"/&gt;
 *         &lt;element name="ElevenRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ElevenRecordDataElement"/&gt;
 *         &lt;element name="FiftyFourRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FiftyFourRecordDataElement"/&gt;
 *         &lt;element name="FiftyOneRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FiftyOneRecordDataElement"/&gt;
 *         &lt;element name="FiftyRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FiftyRecordDataElement"/&gt;
 *         &lt;element name="FiftyThreeRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FiftyThreeRecordDataElement"/&gt;
 *         &lt;element name="FiftyTwoRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FiftyTwoRecordDataElement"/&gt;
 *         &lt;element name="FortyOneRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FortyOneRecordDataElement"/&gt;
 *         &lt;element name="FortyFourRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FortyFourRecordDataElement"/&gt;
 *         &lt;element name="FortyRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FortyRecordDataElement"/&gt;
 *         &lt;element name="FortySevenRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FortySevenRecordDataElement"/&gt;
 *         &lt;element name="FortyThreeRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FortyThreeRecordDataElement"/&gt;
 *         &lt;element name="FortyTwoRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}FortyTwoRecordDataElement"/&gt;
 *         &lt;element name="NinetyRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}NinetyRecordDataElement"/&gt;
 *         &lt;element name="SixtyOneRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}SixtyOneRecordDataElement"/&gt;
 *         &lt;element name="SixtyRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}SixtyRecordDataElement"/&gt;
 *         &lt;element name="SixtyThreeRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}SixtyThreeRecordDataElement"/&gt;
 *         &lt;element name="SixtyTwoRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}SixtyTwoRecordDataElement"/&gt;
 *         &lt;element name="TenRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}TenRecordDataElement"/&gt;
 *         &lt;element name="ThirtyFiveRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ThirtyFiveRecordDataElement"/&gt;
 *         &lt;element name="ThirtyFourRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ThirtyFourRecordDataElement"/&gt;
 *         &lt;element name="ThirtyOneRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ThirtyOneRecordDataElement"/&gt;
 *         &lt;element name="ThirtyRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ThirtyRecordDataElement"/&gt;
 *         &lt;element name="ThirtySixRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ThirtySixRecordDataElement"/&gt;
 *         &lt;element name="ThirtyThreeRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ThirtyThreeRecordDataElement"/&gt;
 *         &lt;element name="ThirtyTwoRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}ThirtyTwoRecordDataElement"/&gt;
 *         &lt;element name="TwentyOneRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}TwentyOneRecordDataElement"/&gt;
 *         &lt;element name="TwentyRecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/numbers}TwentyRecordDataElement"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Numbers", propOrder = {
    "eightyEightRecordDataElement",
    "eightyNineRecordDataElement",
    "elevenRecordDataElement",
    "fiftyFourRecordDataElement",
    "fiftyOneRecordDataElement",
    "fiftyRecordDataElement",
    "fiftyThreeRecordDataElement",
    "fiftyTwoRecordDataElement",
    "fortyOneRecordDataElement",
    "fortyFourRecordDataElement",
    "fortyRecordDataElement",
    "fortySevenRecordDataElement",
    "fortyThreeRecordDataElement",
    "fortyTwoRecordDataElement",
    "ninetyRecordDataElement",
    "sixtyOneRecordDataElement",
    "sixtyRecordDataElement",
    "sixtyThreeRecordDataElement",
    "sixtyTwoRecordDataElement",
    "tenRecordDataElement",
    "thirtyFiveRecordDataElement",
    "thirtyFourRecordDataElement",
    "thirtyOneRecordDataElement",
    "thirtyRecordDataElement",
    "thirtySixRecordDataElement",
    "thirtyThreeRecordDataElement",
    "thirtyTwoRecordDataElement",
    "twentyOneRecordDataElement",
    "twentyRecordDataElement"
})
public class Numbers {

    @XmlElement(name = "EightyEightRecordDataElement", required = true)
    protected EightyEightRecordDataElement eightyEightRecordDataElement;
    @XmlElement(name = "EightyNineRecordDataElement", required = true)
    protected EightyNineRecordDataElement eightyNineRecordDataElement;
    @XmlElement(name = "ElevenRecordDataElement", required = true)
    protected ElevenRecordDataElement elevenRecordDataElement;
    @XmlElement(name = "FiftyFourRecordDataElement", required = true)
    protected FiftyFourRecordDataElement fiftyFourRecordDataElement;
    @XmlElement(name = "FiftyOneRecordDataElement", required = true)
    protected FiftyOneRecordDataElement fiftyOneRecordDataElement;
    @XmlElement(name = "FiftyRecordDataElement", required = true)
    protected FiftyRecordDataElement fiftyRecordDataElement;
    @XmlElement(name = "FiftyThreeRecordDataElement", required = true)
    protected FiftyThreeRecordDataElement fiftyThreeRecordDataElement;
    @XmlElement(name = "FiftyTwoRecordDataElement", required = true)
    protected FiftyTwoRecordDataElement fiftyTwoRecordDataElement;
    @XmlElement(name = "FortyOneRecordDataElement", required = true)
    protected FortyOneRecordDataElement fortyOneRecordDataElement;
    @XmlElement(name = "FortyFourRecordDataElement", required = true)
    protected FortyFourRecordDataElement fortyFourRecordDataElement;
    @XmlElement(name = "FortyRecordDataElement", required = true)
    protected FortyRecordDataElement fortyRecordDataElement;
    @XmlElement(name = "FortySevenRecordDataElement", required = true)
    protected FortySevenRecordDataElement fortySevenRecordDataElement;
    @XmlElement(name = "FortyThreeRecordDataElement", required = true)
    protected FortyThreeRecordDataElement fortyThreeRecordDataElement;
    @XmlElement(name = "FortyTwoRecordDataElement", required = true)
    protected FortyTwoRecordDataElement fortyTwoRecordDataElement;
    @XmlElement(name = "NinetyRecordDataElement", required = true)
    protected NinetyRecordDataElement ninetyRecordDataElement;
    @XmlElement(name = "SixtyOneRecordDataElement", required = true)
    protected SixtyOneRecordDataElement sixtyOneRecordDataElement;
    @XmlElement(name = "SixtyRecordDataElement", required = true)
    protected SixtyRecordDataElement sixtyRecordDataElement;
    @XmlElement(name = "SixtyThreeRecordDataElement", required = true)
    protected SixtyThreeRecordDataElement sixtyThreeRecordDataElement;
    @XmlElement(name = "SixtyTwoRecordDataElement", required = true)
    protected SixtyTwoRecordDataElement sixtyTwoRecordDataElement;
    @XmlElement(name = "TenRecordDataElement", required = true)
    protected TenRecordDataElement tenRecordDataElement;
    @XmlElement(name = "ThirtyFiveRecordDataElement", required = true)
    protected ThirtyFiveRecordDataElement thirtyFiveRecordDataElement;
    @XmlElement(name = "ThirtyFourRecordDataElement", required = true)
    protected ThirtyFourRecordDataElement thirtyFourRecordDataElement;
    @XmlElement(name = "ThirtyOneRecordDataElement", required = true)
    protected ThirtyOneRecordDataElement thirtyOneRecordDataElement;
    @XmlElement(name = "ThirtyRecordDataElement", required = true)
    protected ThirtyRecordDataElement thirtyRecordDataElement;
    @XmlElement(name = "ThirtySixRecordDataElement", required = true)
    protected ThirtySixRecordDataElement thirtySixRecordDataElement;
    @XmlElement(name = "ThirtyThreeRecordDataElement", required = true)
    protected ThirtyThreeRecordDataElement thirtyThreeRecordDataElement;
    @XmlElement(name = "ThirtyTwoRecordDataElement", required = true)
    protected ThirtyTwoRecordDataElement thirtyTwoRecordDataElement;
    @XmlElement(name = "TwentyOneRecordDataElement", required = true)
    protected TwentyOneRecordDataElement twentyOneRecordDataElement;
    @XmlElement(name = "TwentyRecordDataElement", required = true)
    protected TwentyRecordDataElement twentyRecordDataElement;

    /**
     * Gets the value of the eightyEightRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link EightyEightRecordDataElement }
     *     
     */
    public EightyEightRecordDataElement getEightyEightRecordDataElement() {
        return eightyEightRecordDataElement;
    }

    /**
     * Sets the value of the eightyEightRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link EightyEightRecordDataElement }
     *     
     */
    public void setEightyEightRecordDataElement(EightyEightRecordDataElement value) {
        this.eightyEightRecordDataElement = value;
    }

    /**
     * Gets the value of the eightyNineRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link EightyNineRecordDataElement }
     *     
     */
    public EightyNineRecordDataElement getEightyNineRecordDataElement() {
        return eightyNineRecordDataElement;
    }

    /**
     * Sets the value of the eightyNineRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link EightyNineRecordDataElement }
     *     
     */
    public void setEightyNineRecordDataElement(EightyNineRecordDataElement value) {
        this.eightyNineRecordDataElement = value;
    }

    /**
     * Gets the value of the elevenRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ElevenRecordDataElement }
     *     
     */
    public ElevenRecordDataElement getElevenRecordDataElement() {
        return elevenRecordDataElement;
    }

    /**
     * Sets the value of the elevenRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElevenRecordDataElement }
     *     
     */
    public void setElevenRecordDataElement(ElevenRecordDataElement value) {
        this.elevenRecordDataElement = value;
    }

    /**
     * Gets the value of the fiftyFourRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FiftyFourRecordDataElement }
     *     
     */
    public FiftyFourRecordDataElement getFiftyFourRecordDataElement() {
        return fiftyFourRecordDataElement;
    }

    /**
     * Sets the value of the fiftyFourRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiftyFourRecordDataElement }
     *     
     */
    public void setFiftyFourRecordDataElement(FiftyFourRecordDataElement value) {
        this.fiftyFourRecordDataElement = value;
    }

    /**
     * Gets the value of the fiftyOneRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FiftyOneRecordDataElement }
     *     
     */
    public FiftyOneRecordDataElement getFiftyOneRecordDataElement() {
        return fiftyOneRecordDataElement;
    }

    /**
     * Sets the value of the fiftyOneRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiftyOneRecordDataElement }
     *     
     */
    public void setFiftyOneRecordDataElement(FiftyOneRecordDataElement value) {
        this.fiftyOneRecordDataElement = value;
    }

    /**
     * Gets the value of the fiftyRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FiftyRecordDataElement }
     *     
     */
    public FiftyRecordDataElement getFiftyRecordDataElement() {
        return fiftyRecordDataElement;
    }

    /**
     * Sets the value of the fiftyRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiftyRecordDataElement }
     *     
     */
    public void setFiftyRecordDataElement(FiftyRecordDataElement value) {
        this.fiftyRecordDataElement = value;
    }

    /**
     * Gets the value of the fiftyThreeRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FiftyThreeRecordDataElement }
     *     
     */
    public FiftyThreeRecordDataElement getFiftyThreeRecordDataElement() {
        return fiftyThreeRecordDataElement;
    }

    /**
     * Sets the value of the fiftyThreeRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiftyThreeRecordDataElement }
     *     
     */
    public void setFiftyThreeRecordDataElement(FiftyThreeRecordDataElement value) {
        this.fiftyThreeRecordDataElement = value;
    }

    /**
     * Gets the value of the fiftyTwoRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FiftyTwoRecordDataElement }
     *     
     */
    public FiftyTwoRecordDataElement getFiftyTwoRecordDataElement() {
        return fiftyTwoRecordDataElement;
    }

    /**
     * Sets the value of the fiftyTwoRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiftyTwoRecordDataElement }
     *     
     */
    public void setFiftyTwoRecordDataElement(FiftyTwoRecordDataElement value) {
        this.fiftyTwoRecordDataElement = value;
    }

    /**
     * Gets the value of the fortyOneRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FortyOneRecordDataElement }
     *     
     */
    public FortyOneRecordDataElement getFortyOneRecordDataElement() {
        return fortyOneRecordDataElement;
    }

    /**
     * Sets the value of the fortyOneRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FortyOneRecordDataElement }
     *     
     */
    public void setFortyOneRecordDataElement(FortyOneRecordDataElement value) {
        this.fortyOneRecordDataElement = value;
    }

    /**
     * Gets the value of the fortyFourRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FortyFourRecordDataElement }
     *     
     */
    public FortyFourRecordDataElement getFortyFourRecordDataElement() {
        return fortyFourRecordDataElement;
    }

    /**
     * Sets the value of the fortyFourRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FortyFourRecordDataElement }
     *     
     */
    public void setFortyFourRecordDataElement(FortyFourRecordDataElement value) {
        this.fortyFourRecordDataElement = value;
    }

    /**
     * Gets the value of the fortyRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FortyRecordDataElement }
     *     
     */
    public FortyRecordDataElement getFortyRecordDataElement() {
        return fortyRecordDataElement;
    }

    /**
     * Sets the value of the fortyRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FortyRecordDataElement }
     *     
     */
    public void setFortyRecordDataElement(FortyRecordDataElement value) {
        this.fortyRecordDataElement = value;
    }

    /**
     * Gets the value of the fortySevenRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FortySevenRecordDataElement }
     *     
     */
    public FortySevenRecordDataElement getFortySevenRecordDataElement() {
        return fortySevenRecordDataElement;
    }

    /**
     * Sets the value of the fortySevenRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FortySevenRecordDataElement }
     *     
     */
    public void setFortySevenRecordDataElement(FortySevenRecordDataElement value) {
        this.fortySevenRecordDataElement = value;
    }

    /**
     * Gets the value of the fortyThreeRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FortyThreeRecordDataElement }
     *     
     */
    public FortyThreeRecordDataElement getFortyThreeRecordDataElement() {
        return fortyThreeRecordDataElement;
    }

    /**
     * Sets the value of the fortyThreeRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FortyThreeRecordDataElement }
     *     
     */
    public void setFortyThreeRecordDataElement(FortyThreeRecordDataElement value) {
        this.fortyThreeRecordDataElement = value;
    }

    /**
     * Gets the value of the fortyTwoRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link FortyTwoRecordDataElement }
     *     
     */
    public FortyTwoRecordDataElement getFortyTwoRecordDataElement() {
        return fortyTwoRecordDataElement;
    }

    /**
     * Sets the value of the fortyTwoRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FortyTwoRecordDataElement }
     *     
     */
    public void setFortyTwoRecordDataElement(FortyTwoRecordDataElement value) {
        this.fortyTwoRecordDataElement = value;
    }

    /**
     * Gets the value of the ninetyRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link NinetyRecordDataElement }
     *     
     */
    public NinetyRecordDataElement getNinetyRecordDataElement() {
        return ninetyRecordDataElement;
    }

    /**
     * Sets the value of the ninetyRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link NinetyRecordDataElement }
     *     
     */
    public void setNinetyRecordDataElement(NinetyRecordDataElement value) {
        this.ninetyRecordDataElement = value;
    }

    /**
     * Gets the value of the sixtyOneRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SixtyOneRecordDataElement }
     *     
     */
    public SixtyOneRecordDataElement getSixtyOneRecordDataElement() {
        return sixtyOneRecordDataElement;
    }

    /**
     * Sets the value of the sixtyOneRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SixtyOneRecordDataElement }
     *     
     */
    public void setSixtyOneRecordDataElement(SixtyOneRecordDataElement value) {
        this.sixtyOneRecordDataElement = value;
    }

    /**
     * Gets the value of the sixtyRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SixtyRecordDataElement }
     *     
     */
    public SixtyRecordDataElement getSixtyRecordDataElement() {
        return sixtyRecordDataElement;
    }

    /**
     * Sets the value of the sixtyRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SixtyRecordDataElement }
     *     
     */
    public void setSixtyRecordDataElement(SixtyRecordDataElement value) {
        this.sixtyRecordDataElement = value;
    }

    /**
     * Gets the value of the sixtyThreeRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SixtyThreeRecordDataElement }
     *     
     */
    public SixtyThreeRecordDataElement getSixtyThreeRecordDataElement() {
        return sixtyThreeRecordDataElement;
    }

    /**
     * Sets the value of the sixtyThreeRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SixtyThreeRecordDataElement }
     *     
     */
    public void setSixtyThreeRecordDataElement(SixtyThreeRecordDataElement value) {
        this.sixtyThreeRecordDataElement = value;
    }

    /**
     * Gets the value of the sixtyTwoRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SixtyTwoRecordDataElement }
     *     
     */
    public SixtyTwoRecordDataElement getSixtyTwoRecordDataElement() {
        return sixtyTwoRecordDataElement;
    }

    /**
     * Sets the value of the sixtyTwoRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SixtyTwoRecordDataElement }
     *     
     */
    public void setSixtyTwoRecordDataElement(SixtyTwoRecordDataElement value) {
        this.sixtyTwoRecordDataElement = value;
    }

    /**
     * Gets the value of the tenRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link TenRecordDataElement }
     *     
     */
    public TenRecordDataElement getTenRecordDataElement() {
        return tenRecordDataElement;
    }

    /**
     * Sets the value of the tenRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenRecordDataElement }
     *     
     */
    public void setTenRecordDataElement(TenRecordDataElement value) {
        this.tenRecordDataElement = value;
    }

    /**
     * Gets the value of the thirtyFiveRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ThirtyFiveRecordDataElement }
     *     
     */
    public ThirtyFiveRecordDataElement getThirtyFiveRecordDataElement() {
        return thirtyFiveRecordDataElement;
    }

    /**
     * Sets the value of the thirtyFiveRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirtyFiveRecordDataElement }
     *     
     */
    public void setThirtyFiveRecordDataElement(ThirtyFiveRecordDataElement value) {
        this.thirtyFiveRecordDataElement = value;
    }

    /**
     * Gets the value of the thirtyFourRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ThirtyFourRecordDataElement }
     *     
     */
    public ThirtyFourRecordDataElement getThirtyFourRecordDataElement() {
        return thirtyFourRecordDataElement;
    }

    /**
     * Sets the value of the thirtyFourRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirtyFourRecordDataElement }
     *     
     */
    public void setThirtyFourRecordDataElement(ThirtyFourRecordDataElement value) {
        this.thirtyFourRecordDataElement = value;
    }

    /**
     * Gets the value of the thirtyOneRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ThirtyOneRecordDataElement }
     *     
     */
    public ThirtyOneRecordDataElement getThirtyOneRecordDataElement() {
        return thirtyOneRecordDataElement;
    }

    /**
     * Sets the value of the thirtyOneRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirtyOneRecordDataElement }
     *     
     */
    public void setThirtyOneRecordDataElement(ThirtyOneRecordDataElement value) {
        this.thirtyOneRecordDataElement = value;
    }

    /**
     * Gets the value of the thirtyRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ThirtyRecordDataElement }
     *     
     */
    public ThirtyRecordDataElement getThirtyRecordDataElement() {
        return thirtyRecordDataElement;
    }

    /**
     * Sets the value of the thirtyRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirtyRecordDataElement }
     *     
     */
    public void setThirtyRecordDataElement(ThirtyRecordDataElement value) {
        this.thirtyRecordDataElement = value;
    }

    /**
     * Gets the value of the thirtySixRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ThirtySixRecordDataElement }
     *     
     */
    public ThirtySixRecordDataElement getThirtySixRecordDataElement() {
        return thirtySixRecordDataElement;
    }

    /**
     * Sets the value of the thirtySixRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirtySixRecordDataElement }
     *     
     */
    public void setThirtySixRecordDataElement(ThirtySixRecordDataElement value) {
        this.thirtySixRecordDataElement = value;
    }

    /**
     * Gets the value of the thirtyThreeRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ThirtyThreeRecordDataElement }
     *     
     */
    public ThirtyThreeRecordDataElement getThirtyThreeRecordDataElement() {
        return thirtyThreeRecordDataElement;
    }

    /**
     * Sets the value of the thirtyThreeRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirtyThreeRecordDataElement }
     *     
     */
    public void setThirtyThreeRecordDataElement(ThirtyThreeRecordDataElement value) {
        this.thirtyThreeRecordDataElement = value;
    }

    /**
     * Gets the value of the thirtyTwoRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link ThirtyTwoRecordDataElement }
     *     
     */
    public ThirtyTwoRecordDataElement getThirtyTwoRecordDataElement() {
        return thirtyTwoRecordDataElement;
    }

    /**
     * Sets the value of the thirtyTwoRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirtyTwoRecordDataElement }
     *     
     */
    public void setThirtyTwoRecordDataElement(ThirtyTwoRecordDataElement value) {
        this.thirtyTwoRecordDataElement = value;
    }

    /**
     * Gets the value of the twentyOneRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link TwentyOneRecordDataElement }
     *     
     */
    public TwentyOneRecordDataElement getTwentyOneRecordDataElement() {
        return twentyOneRecordDataElement;
    }

    /**
     * Sets the value of the twentyOneRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwentyOneRecordDataElement }
     *     
     */
    public void setTwentyOneRecordDataElement(TwentyOneRecordDataElement value) {
        this.twentyOneRecordDataElement = value;
    }

    /**
     * Gets the value of the twentyRecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link TwentyRecordDataElement }
     *     
     */
    public TwentyRecordDataElement getTwentyRecordDataElement() {
        return twentyRecordDataElement;
    }

    /**
     * Sets the value of the twentyRecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwentyRecordDataElement }
     *     
     */
    public void setTwentyRecordDataElement(TwentyRecordDataElement value) {
        this.twentyRecordDataElement = value;
    }

}
