//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 06:55:02 PM EEST 
//


package com.onenetwork.model.ae_ax.se;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.onenetwork.model.ae_ax.se package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.onenetwork.model.ae_ax.se
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SEGlobal }
     * 
     */
    public SEGlobal createSEGlobal() {
        return new SEGlobal();
    }

    /**
     * Create an instance of {@link SE13RecordDataElement }
     * 
     */
    public SE13RecordDataElement createSE13RecordDataElement() {
        return new SE13RecordDataElement();
    }

    /**
     * Create an instance of {@link SE16RecordDataElement }
     * 
     */
    public SE16RecordDataElement createSE16RecordDataElement() {
        return new SE16RecordDataElement();
    }

    /**
     * Create an instance of {@link SE17RecordDataElement }
     * 
     */
    public SE17RecordDataElement createSE17RecordDataElement() {
        return new SE17RecordDataElement();
    }

    /**
     * Create an instance of {@link SE20RecordDataElement }
     * 
     */
    public SE20RecordDataElement createSE20RecordDataElement() {
        return new SE20RecordDataElement();
    }

    /**
     * Create an instance of {@link SE30RecordDataElement }
     * 
     */
    public SE30RecordDataElement createSE30RecordDataElement() {
        return new SE30RecordDataElement();
    }

    /**
     * Create an instance of {@link SE35RecordDataElement }
     * 
     */
    public SE35RecordDataElement createSE35RecordDataElement() {
        return new SE35RecordDataElement();
    }

    /**
     * Create an instance of {@link SE36RecordDataElement }
     * 
     */
    public SE36RecordDataElement createSE36RecordDataElement() {
        return new SE36RecordDataElement();
    }

    /**
     * Create an instance of {@link SE50RecordDataElement }
     * 
     */
    public SE50RecordDataElement createSE50RecordDataElement() {
        return new SE50RecordDataElement();
    }

    /**
     * Create an instance of {@link SE55RecordDataElement }
     * 
     */
    public SE55RecordDataElement createSE55RecordDataElement() {
        return new SE55RecordDataElement();
    }

    /**
     * Create an instance of {@link SE56RecordDataElement }
     * 
     */
    public SE56RecordDataElement createSE56RecordDataElement() {
        return new SE56RecordDataElement();
    }

    /**
     * Create an instance of {@link SE61RecordDataElement }
     * 
     */
    public SE61RecordDataElement createSE61RecordDataElement() {
        return new SE61RecordDataElement();
    }

}
