//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 05:38:52 PM EEST 
//


package com.onenetwork.model.ae_ax.se;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SEGlobal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SEGlobal"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SE13RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE13RecordDataElement"/&gt;
 *         &lt;element name="SE16RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE16RecordDataElement"/&gt;
 *         &lt;element name="SE17RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE17RecordDataElement"/&gt;
 *         &lt;element name="SE20RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE20RecordDataElement"/&gt;
 *         &lt;element name="SE30RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE30RecordDataElement"/&gt;
 *         &lt;element name="SE35RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE35RecordDataElement"/&gt;
 *         &lt;element name="SE36RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE36RecordDataElement"/&gt;
 *         &lt;element name="SE50RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE50RecordDataElement"/&gt;
 *         &lt;element name="SE55RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE55RecordDataElement"/&gt;
 *         &lt;element name="SE56RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE56RecordDataElement"/&gt;
 *         &lt;element name="SE61RecordDataElement" type="{http://www.model.onenetwork.com/ae_ax/se}SE61RecordDataElement"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SEGlobal", propOrder = {
    "se13RecordDataElement",
    "se16RecordDataElement",
    "se17RecordDataElement",
    "se20RecordDataElement",
    "se30RecordDataElement",
    "se35RecordDataElement",
    "se36RecordDataElement",
    "se50RecordDataElement",
    "se55RecordDataElement",
    "se56RecordDataElement",
    "se61RecordDataElement"
})
public class SEGlobal {

    @XmlElement(name = "SE13RecordDataElement", required = true)
    protected SE13RecordDataElement se13RecordDataElement;
    @XmlElement(name = "SE16RecordDataElement", required = true)
    protected SE16RecordDataElement se16RecordDataElement;
    @XmlElement(name = "SE17RecordDataElement", required = true)
    protected SE17RecordDataElement se17RecordDataElement;
    @XmlElement(name = "SE20RecordDataElement", required = true)
    protected SE20RecordDataElement se20RecordDataElement;
    @XmlElement(name = "SE30RecordDataElement", required = true)
    protected SE30RecordDataElement se30RecordDataElement;
    @XmlElement(name = "SE35RecordDataElement", required = true)
    protected SE35RecordDataElement se35RecordDataElement;
    @XmlElement(name = "SE36RecordDataElement", required = true)
    protected SE36RecordDataElement se36RecordDataElement;
    @XmlElement(name = "SE50RecordDataElement", required = true)
    protected SE50RecordDataElement se50RecordDataElement;
    @XmlElement(name = "SE55RecordDataElement", required = true)
    protected SE55RecordDataElement se55RecordDataElement;
    @XmlElement(name = "SE56RecordDataElement", required = true)
    protected SE56RecordDataElement se56RecordDataElement;
    @XmlElement(name = "SE61RecordDataElement", required = true)
    protected SE61RecordDataElement se61RecordDataElement;

    /**
     * Gets the value of the se13RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE13RecordDataElement }
     *     
     */
    public SE13RecordDataElement getSE13RecordDataElement() {
        return se13RecordDataElement;
    }

    /**
     * Sets the value of the se13RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE13RecordDataElement }
     *     
     */
    public void setSE13RecordDataElement(SE13RecordDataElement value) {
        this.se13RecordDataElement = value;
    }

    /**
     * Gets the value of the se16RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE16RecordDataElement }
     *     
     */
    public SE16RecordDataElement getSE16RecordDataElement() {
        return se16RecordDataElement;
    }

    /**
     * Sets the value of the se16RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE16RecordDataElement }
     *     
     */
    public void setSE16RecordDataElement(SE16RecordDataElement value) {
        this.se16RecordDataElement = value;
    }

    /**
     * Gets the value of the se17RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE17RecordDataElement }
     *     
     */
    public SE17RecordDataElement getSE17RecordDataElement() {
        return se17RecordDataElement;
    }

    /**
     * Sets the value of the se17RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE17RecordDataElement }
     *     
     */
    public void setSE17RecordDataElement(SE17RecordDataElement value) {
        this.se17RecordDataElement = value;
    }

    /**
     * Gets the value of the se20RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE20RecordDataElement }
     *     
     */
    public SE20RecordDataElement getSE20RecordDataElement() {
        return se20RecordDataElement;
    }

    /**
     * Sets the value of the se20RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE20RecordDataElement }
     *     
     */
    public void setSE20RecordDataElement(SE20RecordDataElement value) {
        this.se20RecordDataElement = value;
    }

    /**
     * Gets the value of the se30RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE30RecordDataElement }
     *     
     */
    public SE30RecordDataElement getSE30RecordDataElement() {
        return se30RecordDataElement;
    }

    /**
     * Sets the value of the se30RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE30RecordDataElement }
     *     
     */
    public void setSE30RecordDataElement(SE30RecordDataElement value) {
        this.se30RecordDataElement = value;
    }

    /**
     * Gets the value of the se35RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE35RecordDataElement }
     *     
     */
    public SE35RecordDataElement getSE35RecordDataElement() {
        return se35RecordDataElement;
    }

    /**
     * Sets the value of the se35RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE35RecordDataElement }
     *     
     */
    public void setSE35RecordDataElement(SE35RecordDataElement value) {
        this.se35RecordDataElement = value;
    }

    /**
     * Gets the value of the se36RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE36RecordDataElement }
     *     
     */
    public SE36RecordDataElement getSE36RecordDataElement() {
        return se36RecordDataElement;
    }

    /**
     * Sets the value of the se36RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE36RecordDataElement }
     *     
     */
    public void setSE36RecordDataElement(SE36RecordDataElement value) {
        this.se36RecordDataElement = value;
    }

    /**
     * Gets the value of the se50RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE50RecordDataElement }
     *     
     */
    public SE50RecordDataElement getSE50RecordDataElement() {
        return se50RecordDataElement;
    }

    /**
     * Sets the value of the se50RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE50RecordDataElement }
     *     
     */
    public void setSE50RecordDataElement(SE50RecordDataElement value) {
        this.se50RecordDataElement = value;
    }

    /**
     * Gets the value of the se55RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE55RecordDataElement }
     *     
     */
    public SE55RecordDataElement getSE55RecordDataElement() {
        return se55RecordDataElement;
    }

    /**
     * Sets the value of the se55RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE55RecordDataElement }
     *     
     */
    public void setSE55RecordDataElement(SE55RecordDataElement value) {
        this.se55RecordDataElement = value;
    }

    /**
     * Gets the value of the se56RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE56RecordDataElement }
     *     
     */
    public SE56RecordDataElement getSE56RecordDataElement() {
        return se56RecordDataElement;
    }

    /**
     * Sets the value of the se56RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE56RecordDataElement }
     *     
     */
    public void setSE56RecordDataElement(SE56RecordDataElement value) {
        this.se56RecordDataElement = value;
    }

    /**
     * Gets the value of the se61RecordDataElement property.
     * 
     * @return
     *     possible object is
     *     {@link SE61RecordDataElement }
     *     
     */
    public SE61RecordDataElement getSE61RecordDataElement() {
        return se61RecordDataElement;
    }

    /**
     * Sets the value of the se61RecordDataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SE61RecordDataElement }
     *     
     */
    public void setSE61RecordDataElement(SE61RecordDataElement value) {
        this.se61RecordDataElement = value;
    }

}
