//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 06:55:02 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.model.onenetwork.com/isf_model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.onenetwork.model.isf_model;
