//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.19 at 01:39:53 PM EEST 
//


package com.onenetwork.model.ae_ax.cw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.onenetwork.model.positions.Positions;


/**
 * <p>Java class for CW02RecordDataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CW02RecordDataElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="controlIdentifier" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionCodeFirst" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionOverrideCodeFirst" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionCodeSecond" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionOverrideCodeSecond" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionOverrideCodeThird" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionOverrideCodeFourth" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionCodeFifth" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionOverrideCodeFifth" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionCodeSixth" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionCodeSeventh" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *         &lt;element name="censusWarningConditionOverrideCodeSeventh" type="{http://www.model.onenetwork.com/positions}Positions"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CW02RecordDataElement", propOrder = {
    "controlIdentifier",
    "censusWarningConditionCodeFirst",
    "censusWarningConditionOverrideCodeFirst",
    "censusWarningConditionCodeSecond",
    "censusWarningConditionOverrideCodeSecond",
    "censusWarningConditionOverrideCodeThird",
    "censusWarningConditionOverrideCodeFourth",
    "censusWarningConditionCodeFifth",
    "censusWarningConditionOverrideCodeFifth",
    "censusWarningConditionCodeSixth",
    "censusWarningConditionCodeSeventh",
    "censusWarningConditionOverrideCodeSeventh"
})
public class CW02RecordDataElement {

    protected Positions controlIdentifier;
    protected Positions censusWarningConditionCodeFirst;
    protected Positions censusWarningConditionOverrideCodeFirst;
    protected Positions censusWarningConditionCodeSecond;
    protected Positions censusWarningConditionOverrideCodeSecond;
    protected Positions censusWarningConditionOverrideCodeThird;
    protected Positions censusWarningConditionOverrideCodeFourth;
    protected Positions censusWarningConditionCodeFifth;
    protected Positions censusWarningConditionOverrideCodeFifth;
    protected Positions censusWarningConditionCodeSixth;
    protected Positions censusWarningConditionCodeSeventh;
    protected Positions censusWarningConditionOverrideCodeSeventh;

    /**
     * Gets the value of the controlIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getControlIdentifier() {
        return controlIdentifier;
    }

    /**
     * Sets the value of the controlIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setControlIdentifier(Positions value) {
        this.controlIdentifier = value;
    }

    /**
     * Gets the value of the censusWarningConditionCodeFirst property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionCodeFirst() {
        return censusWarningConditionCodeFirst;
    }

    /**
     * Sets the value of the censusWarningConditionCodeFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionCodeFirst(Positions value) {
        this.censusWarningConditionCodeFirst = value;
    }

    /**
     * Gets the value of the censusWarningConditionOverrideCodeFirst property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionOverrideCodeFirst() {
        return censusWarningConditionOverrideCodeFirst;
    }

    /**
     * Sets the value of the censusWarningConditionOverrideCodeFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionOverrideCodeFirst(Positions value) {
        this.censusWarningConditionOverrideCodeFirst = value;
    }

    /**
     * Gets the value of the censusWarningConditionCodeSecond property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionCodeSecond() {
        return censusWarningConditionCodeSecond;
    }

    /**
     * Sets the value of the censusWarningConditionCodeSecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionCodeSecond(Positions value) {
        this.censusWarningConditionCodeSecond = value;
    }

    /**
     * Gets the value of the censusWarningConditionOverrideCodeSecond property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionOverrideCodeSecond() {
        return censusWarningConditionOverrideCodeSecond;
    }

    /**
     * Sets the value of the censusWarningConditionOverrideCodeSecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionOverrideCodeSecond(Positions value) {
        this.censusWarningConditionOverrideCodeSecond = value;
    }

    /**
     * Gets the value of the censusWarningConditionOverrideCodeThird property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionOverrideCodeThird() {
        return censusWarningConditionOverrideCodeThird;
    }

    /**
     * Sets the value of the censusWarningConditionOverrideCodeThird property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionOverrideCodeThird(Positions value) {
        this.censusWarningConditionOverrideCodeThird = value;
    }

    /**
     * Gets the value of the censusWarningConditionOverrideCodeFourth property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionOverrideCodeFourth() {
        return censusWarningConditionOverrideCodeFourth;
    }

    /**
     * Sets the value of the censusWarningConditionOverrideCodeFourth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionOverrideCodeFourth(Positions value) {
        this.censusWarningConditionOverrideCodeFourth = value;
    }

    /**
     * Gets the value of the censusWarningConditionCodeFifth property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionCodeFifth() {
        return censusWarningConditionCodeFifth;
    }

    /**
     * Sets the value of the censusWarningConditionCodeFifth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionCodeFifth(Positions value) {
        this.censusWarningConditionCodeFifth = value;
    }

    /**
     * Gets the value of the censusWarningConditionOverrideCodeFifth property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionOverrideCodeFifth() {
        return censusWarningConditionOverrideCodeFifth;
    }

    /**
     * Sets the value of the censusWarningConditionOverrideCodeFifth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionOverrideCodeFifth(Positions value) {
        this.censusWarningConditionOverrideCodeFifth = value;
    }

    /**
     * Gets the value of the censusWarningConditionCodeSixth property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionCodeSixth() {
        return censusWarningConditionCodeSixth;
    }

    /**
     * Sets the value of the censusWarningConditionCodeSixth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionCodeSixth(Positions value) {
        this.censusWarningConditionCodeSixth = value;
    }

    /**
     * Gets the value of the censusWarningConditionCodeSeventh property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionCodeSeventh() {
        return censusWarningConditionCodeSeventh;
    }

    /**
     * Sets the value of the censusWarningConditionCodeSeventh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionCodeSeventh(Positions value) {
        this.censusWarningConditionCodeSeventh = value;
    }

    /**
     * Gets the value of the censusWarningConditionOverrideCodeSeventh property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getCensusWarningConditionOverrideCodeSeventh() {
        return censusWarningConditionOverrideCodeSeventh;
    }

    /**
     * Sets the value of the censusWarningConditionOverrideCodeSeventh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setCensusWarningConditionOverrideCodeSeventh(Positions value) {
        this.censusWarningConditionOverrideCodeSeventh = value;
    }

}
